from evaluation import InputPreProcessor
from transformers import AutoTokenizer

huggingface_model = 'dslim/bert-base-NER'
tokenizer: AutoTokenizer = AutoTokenizer.from_pretrained(huggingface_model)
label2id = {'O': 0, 'Chemical': 1, 'Disease': 2}


def test_call():
    sut = InputPreProcessor(tokenizer, label2id, 512)
    example_document = get_example_document()
    result = sut(example_document)


def get_example_document():
    return {'id': '0',
            'document_id': '227508',
            'passages': [{'id': '1',
                          'type': 'title',
                          'text': ['Naloxone reverses the antihypertensive effect of clonidine.'],
                          'offsets': [[0, 59]]},
                         {'id': '2',
                          'type': 'abstract',
                          'text': ['In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.'],
                          'offsets': [[60, 1135]]}],
            'entities': [{'id': '3',
                          'type': 'Chemical',
                          'text': ['Naloxone'],
                          'offsets': [[0, 8]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]},
                         {'id': '4',
                          'type': 'Chemical',
                          'text': ['clonidine'],
                          'offsets': [[49, 58]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]},
                         {'id': '5',
                          'type': 'Disease',
                          'text': ['hypertensive'],
                          'offsets': [[93, 105]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D006973'}]},
                         {'id': '6',
                          'type': 'Chemical',
                          'text': ['clonidine'],
                          'offsets': [[181, 190]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]},
                         {'id': '7',
                          'type': 'Chemical',
                          'text': ['nalozone'],
                          'offsets': [[244, 252]],
                          'normalized': []},
                         {'id': '8',
                          'type': 'Disease',
                          'text': ['hypotensive'],
                          'offsets': [[274, 285]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D007022'}]},
                         {'id': '9',
                          'type': 'Chemical',
                          'text': ['alpha-methyldopa'],
                          'offsets': [[306, 322]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D008750'}]},
                         {'id': '10',
                          'type': 'Chemical',
                          'text': ['naloxone'],
                          'offsets': [[354, 362]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]},
                         {'id': '11',
                          'type': 'Chemical',
                          'text': ['Naloxone'],
                          'offsets': [[364, 372]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]},
                         {'id': '12',
                          'type': 'Disease',
                          'text': ['hypertensive'],
                          'offsets': [[469, 481]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D006973'}]},
                         {'id': '13',
                          'type': 'Chemical',
                          'text': ['clonidine'],
                          'offsets': [[487, 496]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]},
                         {'id': '14',
                          'type': 'Chemical',
                          'text': ['[3H]-naloxone'],
                          'offsets': [[563, 576]],
                          'normalized': []},
                         {'id': '15',
                          'type': 'Chemical',
                          'text': ['naloxone'],
                          'offsets': [[589, 597]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]},
                         {'id': '16',
                          'type': 'Chemical',
                          'text': ['clonidine'],
                          'offsets': [[637, 646]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]},
                         {'id': '17',
                          'type': 'Chemical',
                          'text': ['[3H]-dihydroergocryptine'],
                          'offsets': [[671, 695]],
                          'normalized': []},
                         {'id': '18',
                          'type': 'Disease',
                          'text': ['hypertensive'],
                          'offsets': [[750, 762]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D006973'}]},
                         {'id': '19',
                          'type': 'Chemical',
                          'text': ['naloxone'],
                          'offsets': [[865, 873]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]},
                         {'id': '20',
                          'type': 'Chemical',
                          'text': ['clonidine'],
                          'offsets': [[878, 887]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]},
                         {'id': '21',
                          'type': 'Chemical',
                          'text': ['clonidine'],
                          'offsets': [[1026, 1035]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]},
                         {'id': '22',
                          'type': 'Chemical',
                          'text': ['alpha-methyldopa'],
                          'offsets': [[1039, 1055]],
                          'normalized': [{'db_name': 'MESH', 'db_id': 'D008750'}]}],
            'events': [],
            'coreferences': [],
            'relations': [{'id': '23',
                           'type': 'CID',
                           'arg1_id': '9',
                           'arg2_id': '8',
                           'normalized': []},
                          {'id': '24',
                           'type': 'CID',
                           'arg1_id': '22',
                           'arg2_id': '8',
                           'normalized': []}]}